# Generated by Django 3.0.3 on 2020-03-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tett',
            name='sub1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tett',
            name='sub2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
